[workspace]
resolver = "2"
members = [
    "dcli",
    "dsh_api",
]

[workspace.package]
authors = ["Wilbert Schelvis <wilbert.schelvis@kpn.com"]
description = "Command line tool for DSH api"
edition = "2021"
rust-version = "1.77"
version = "0.1.1"
publish = ["artifactory"]
