#![allow(dead_code)]

use std::fmt::{Display, Formatter};

use serde::{Deserialize, Serialize};

#[allow(unused_imports)]
use crate::processor::ProcessorId;
#[allow(unused_imports)]
use crate::version::Version;
use crate::{config_dir_name, identifier};

pub mod pipeline;
pub mod pipeline_config;
pub mod pipeline_descriptor;
pub mod pipeline_registry;

identifier!(
  "trifonius_engine::pipeline",
  PipelineId,
  "pipeline id",
  "^[a-z][a-z0-9]{0,17}$",
  "validpipelineid",
  "invalid.pipeline.id",
  /// A `PipelineId` (together with a [`Version`]) uniquely identifies a declared and saved pipeline
  /// as it will be managed by Trifonius.
  /// A `PipelineId` will be generated by the backend when a pipeline is first
  /// declared/saved. The backend will attempt to generate a more or less readable name,
  /// based on the user-friendly name that was provided with the first declaration.
  ///
  /// Note that for some processor technologies (`dshapp` and `dshservice`) the `PipelineId`
  /// will be used to construct the name of a deployed service on the DSH (together with a
  /// [`ProcessorId`]), yielding a [`PipelineProcessorId`].
  /// Therefor both the `PipelineId` needs to adhere to strict rules
  /// regarding length and syntax.
);
identifier!(
  "trifonius_engine::pipeline",
  PipelineProcessorId,
  "pipeline-processor id",
  "^[a-z][a-z0-9]{0,17}-[a-z][a-z0-9]{0,17}$",
  "validid-validid",
  "validid_validid",
  /// A `PipelineProcessorId` uniquely identifies a configured processor in the scope of a pipeline.
  /// A `PipelineProcessorId` will be defined by the pipeline designer.
  ///
  /// Note that for some processor technologies (`dshapp` and `dshservice`) the `PipelineProcessorId`
  /// will be used to construct the name of a deployed service on the DSH.
  /// Therefor the `PipelineProcessorId` needs to adhere to strict rules
  /// regarding length and syntax.
);
identifier!(
  "trifonius_engine::pipeline",
  PipelineResourceId,
  "pipeline-resource id",
  "^[a-z][a-z0-9]{0,17}-[a-z][a-z0-9]{0,17}$",
  "validid-validid",
  "validid_validid",
  /// A `PipelineResourceId` uniquely identifies a configured resource in the scope of a pipeline.
  /// A `PipelineResourceId` will be defined by the pipeline designer.
  ///
  /// Note that some future resource technologies might potentially use the `PipelineResourceId`
  /// to construct the name of a deployed service on the DSH.
  /// Therefor the `PipelineResourceId` needs to adhere to strict rules
  /// regarding length and syntax.
);

// Declared, Configured, Deleted
// NotDeployed, Deployed
// Stopped, Running, Faulty, Killed

// Declared     -             -         DECLARED     Declared
// Configured   NotDeployed   -         CONFIGURED   Configured
// Configured   Deployed      Stopped   DEPLOYED     DeployedStopped
// Configured   Deployed      Running   RUNNING      DeployedRunning
// Configured   Deployed      Faulty    FAULTY       DeployedFaulty
// Configured   Deployed      Killed    KILLED       DeployedKilled
// Deleted      -             -         DELETED      Deleted

// Declared    NotDeployed  Stopped
// Declared    NotDeployed  Running
// Declared    NotDeployed  Faulty
// Declared    NotDeployed  Killed
// Declared    Deployed     Stopped
// Declared    Deployed     Running
// Declared    Deployed     Faulty
// Declared    Deployed     Killed
// Configured  NotDeployed  Stopped
// Configured  NotDeployed  Running
// Configured  NotDeployed  Faulty
// Configured  NotDeployed  Killed
// Configured  Deployed     Stopped
// Configured  Deployed     Running
// Configured  Deployed     Faulty
// Configured  Deployed     Killed
// Deleted     NotDeployed  Stopped
// Deleted     NotDeployed  Running
// Deleted     NotDeployed  Faulty
// Deleted     NotDeployed  Killed
// Deleted     Deployed     Stopped
// Deleted     Deployed     Running
// Deleted     Deployed     Faulty
// Deleted     Deployed     Killed

const CONFIGURED: &str = "configured";
const DECLARED: &str = "declared";
const DELETED: &str = "deleted";
const DEPLOYED: &str = "deployed";
const STARTED: &str = "started";
const STOPPED: &str = "stopped";

#[derive(Clone, Debug, Deserialize, Serialize, Hash, Eq, PartialEq)]
pub enum PipelineState {
  #[serde(rename = "configured")]
  Configured,
  #[serde(rename = "declared")]
  Declared,
  #[serde(rename = "deleted")]
  Deleted,
  #[serde(rename = "deployed")]
  Deployed,
  #[serde(rename = "started")]
  Started,
  #[serde(rename = "stopped")]
  Stopped,
}

impl Display for PipelineState {
  fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
    match &self {
      Self::Configured => write!(f, "{}", CONFIGURED),
      Self::Declared => write!(f, "{}", DECLARED),
      Self::Deleted => write!(f, "{}", DELETED),
      Self::Deployed => write!(f, "{}", DEPLOYED),
      Self::Started => write!(f, "{}", STARTED),
      Self::Stopped => write!(f, "{}", STOPPED),
    }
  }
}

impl PipelineState {
  pub fn description(&self) -> &str {
    match self {
      Self::Configured => "Configured",
      Self::Declared => "Declared",
      Self::Deleted => "Deleted",
      Self::Deployed => "Deployed",
      Self::Started => "Started",
      Self::Stopped => "Stopped",
    }
  }

  pub fn label(&self) -> &str {
    match self {
      Self::Configured => "Configured",
      Self::Declared => "Declared",
      Self::Deleted => "Deleted",
      Self::Deployed => "Deployed",
      Self::Started => "Started",
      Self::Stopped => "Stopped",
    }
  }
}

impl TryFrom<&str> for PipelineState {
  type Error = String;

  fn try_from(value: &str) -> Result<Self, Self::Error> {
    match value {
      CONFIGURED => Ok(Self::Configured),
      DECLARED => Ok(Self::Declared),
      DELETED => Ok(Self::Deleted),
      DEPLOYED => Ok(Self::Deployed),
      STARTED => Ok(Self::Started),
      STOPPED => Ok(Self::Stopped),
      unrecognized => Err(format!("unrecognized pipeline state '{}'", unrecognized)),
    }
  }
}

pub(crate) fn pipeline_config_dir_name() -> String {
  format!("{}/pipelines", config_dir_name())
}
