name: Release

permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    runs-on: ubuntu-latest
    needs: create-release
    strategy:
      matrix:
        features: ['', manage]
        target: [aarch64-apple-darwin, universal-apple-darwin, x86_64-apple-darwin, x86_64-pc-windows-msvc, x86_64-unknown-linux-gnu]
#        include:
#          - target: aarch64-apple-darwin
#            os: macos-latest
#          - target: universal-apple-darwin
#            os: macos-latest
#          - target: x86_64-apple-darwin
#            os: macos-latest
#          - target: x86_64-pc-windows-msvc
#            os: windows-latest
#          - target: x86_64-unknown-linux-gnu
#            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: dsh
          checksum: sha512
          include: LICENSE.md
          target: ${{ matrix.target }}
          archive: $bin${{ matrix.features && '-' || '' }}${{ matrix.features || '' }}-$tag-$target
          features: ${{ matrix.features || '' }}
          tar: unix
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}
