name: Rust

on:
  workflow_dispatch:
# push:
#   branches: [ "master" ]
# pull_request:
#   branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
      - name: Build all features
        run: cargo build --all-features --verbose
      - name: Run tests on all features
        run: cargo test --all-features --verbose
      - name: Run clippy on all features
        run: cargo clippy --all-features
      - name: Run format checker
        run: cargo +nightly fmt --check
