name: Rust

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
      - name: Run unit tests with default features
        run: cargo test --verbose
      - name: Run clippy with default features
        run: cargo clippy
      - name: Run unit tests with all features enabled
        run: cargo test --all-features --verbose
      - name: Run clippy with all features enabled
        run: cargo clippy --all-features
      - name: Run format checker
        run: cargo +nightly fmt --check --all
